version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=dionisio
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"