server:
  ssl:
    enabled: false
  servlet:
    context-path: /api
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://192.168.0.21:5432/dionisio
    username: admin
    password: admin
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

url:
  api: http://192.168.0.21:8080/api

jwt:
  expiration: ${JWTExpirationInHours}
  secret: ${JWTSecret}
  issuer:
    backoffice: ${BackofficeIssuer}
    user: ${UserIssuer}