server:
  ssl:
    enabled: false
  servlet:
    context-path: /api
  port: 8080


spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://192.168.0.21:5432/dionisio}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

url:
  api: ${URL_API:http://192.168.0.21:8080/api}

jwt:
  expiration: ${JWTExpirationInHours:5}
  secret: ${JWTSecret:default-secret}
  issuer:
    backoffice: ${BackofficeIssuer:backoffice-app}
    user: ${UserIssuer:user-app}