name: CI Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle' # Use Gradle caching instead of Maven

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Generate Test Report (HTML)
        run: ./gradlew testReport # Ensure you have a task named `testReport` in your build.gradle

      - name: Upload Test Results (XML)
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/test-results/test/ # Gradle stores test results here by default

      - name: Upload Test Report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: test-report-html
          path: build/reports/tests/test/ # Gradle stores HTML test reports here by default